name: update-versions
description: |
   Update the versions of RHBQ Platform in all active branches

inputs:
  token:
    description: "The token to use to authenticate against GitHub API and to pull/push"
    required: true

runs:
  using: 'composite'
  steps:

    - name: Set up JDK 25
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 25

    - name: Update versions
      shell: bash
      env:
        GITHUB_ISSUE_ID: '1'
        GITHUB_TOKEN: ${{ inputs.token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        JBANG_CATALOG_GIT_REPOSITORY: https://github.com/${{ github.repository }}.git
      run: |
        cd .github/actions/update-versions
        ./mvnw clean test -B -ntp
